### ISSUE TITLE
Font improvements

### ISSUE THREAD

**Issue by da411d** [kookob/toolset-plugin#1]
Hello. I am new user of your plugin and i have some improvement ideas:

In **Toolset** > **Symbol** > **Ascii**: please set monospace font like `consolas` or other so table would be easier to read.
Compare:
<kbd>
![image](https://user-images.githubusercontent.com/12462454/92303137-d661be80-ef7a-11ea-9f66-d5f6bd773573.png)
</kbd>
<kbd>
![image](https://user-images.githubusercontent.com/12462454/92303181-348ea180-ef7b-11ea-8a05-ac4d56511536.png)
</kbd>

Same about other tabs in **Symbol** tab.

Also i think that monospace font will look better in other tabs, such as `convert`, `httpServer`, `regex`, `terminal` etc.

**Comment by kookob** [comment]
Get it, I will take a test.

**Comment by kookob** [comment]
Hello, When I try the new font, and I find some problems. Many monospaced English fonts do not support Unicode characters, so I may keep using the default font to reduce garbled characters

**Comment by kookob** [comment]
Thank you for your suggestion. The new version(2020.10.1) has been optimized.
